
##########CRIANDO TABELA##########

CREATE TABLE COMPRAS (ID NUMBER PRIMARY KEY, VALOR NUMBER, DATA DATE, OBSERVACOES VARCHAR2(30), RECEBIDO CHAR CHECK (RECEBIDO IN (0,1)));

## CRIANDO SEQUENCIA DE ID;

CREATE SEQUENCE ID_SEQ;

## INSERINDO NA TABELA

INSERT INTO COMPRAS (ID, VALOR, DATA, OBSERVACOES, RECEBIDO) VALUES (ID.NEXTVAL, 100, '12-MAY-2017', COMPRAS DE MAIO, '1');
INSERT INTO COMPRAS (ID, VALOR, DATA, OBSERVACOES, RECEBIDO) VALUES (ID.NEXTVAL, 150, '10-JUN-2017', COMPRAS DE JUNHO, '1');

##########SELECTS##########

# APENAS VALOR E DATA

SELECT VALOR, DATA FROM COMPRAS;

#MULTIPLICADO POR 3

SELECT VALOR * 3, DATA FROM COMPRAS;

#ALIAS (RENOMEANDO PARA TRIPLO) MULTIPLICADO POR 3

SELECT VALOR * 3 AS TRIPLO, DATA, FROM COMPRAS;

#SELECIONANDO COMPRAS COM VALOR A CIMA DE 100 REAIS

SELECT VALOR, DATA FROM COMPRAS WHERE VALOR > 100;

#SELECIONANDO COMPRAS MENORES QUE 120;

SELECT VALOR, DATA FROM COMPRAS WHERE VALOR < 120;

#SELECIONANDO VALORES DE COMPRAS MENORES QUE 120 E QUE FORAM RECEBIDAS;

SELECT * FROM COMPRAS WHERE VALOR < 120 AND RECEBIDO = '1';

#SELECIONANDO COMPRAS MENOR DE 120 REIAS OU QUE FOI RECEBIDA (OR)

SELECT * FROM COMPRAS WHERE VALOR < 120 OR RECEBIDO = '1';

#FILTRARNDO PELAS OBSERVACOES (LIKE)

SELECT * FROM COMPRAS WHERE OBSERVACOES LIKE = 'COMPRAS%';

#SELECT COM CONTENHA (ANTES OU DEPOIS)

SELECT * FROM COMPRAS WHERE OBSERVACOES LIKE '%DE%';

#SELECT ENTRE UM VALOR E OUTRO (BETWEEN) , BETWEEN É INCLUSIVO, OU SEJA, SEMPRE EH >= OU <= 

SELECT * FROM COMPRAS WHERE VALOR > 200 AND VALOR <= 700;
SELECT * FROM COMPRAS WHERE VALOR BETWEEN 200 AND 700;
SELECT * FROM COMPRAS WHERE DATA BETWEEN '01-JAN-2010' AND '01-APR-2010';


##########UPDATE##########

UPDATE COMPRAS SET VALOR = 900 WHERE ID = 20;

UPDATE COMPRAS SET VALOR = 100, OBSERVACOES = 'UMA COMPRA COMUM' WHERE DATA NOT BETWEEN '01-JAN-2010' AND '01-APR-2010';

UPDATE COMPRAS SET OBSERVACOES = 'DATAS FESTIVAS' WHERE DATA = '12-OUT-2010' OR DATA = '25-DEC-2010' OR DATA = '12-JUN-2010';

UPDATE COMPRAS SET OBSERVACOES = 'DATAS FESTIVAS' WHERE DATA IN ('12-OUT-2010', '25-DEC-2010', '12-JUN-2010');

##########DELETE##########

DELETE FROM COMPRAS WHERE ID = 44;

DELETE FROM COMPRAS WHERE VALOR < 50;

