DECLARE @Id int,
		@Valor nvarchar(max) -- VALOR A SER COPIADO 
		
		DECLARE c1 CURSOR READ_ONLY
		FOR SELECT ID, COLUNA_COM_INFO  FROM TABLE_FOREACH_PEGA_ID

		OPEN c1

		FETCH NEXT FROM c1
		INTO @Id,
		@Valor

		WHILE @@FETCH_STATUS = 0
		BEGIN

		UPDATE TABLE_FOREACH_PEGA_ID SET COLUNA_VAZIA = @Valor WHERE ID= @Id

		FETCH NEXT FROM c1 INTO @Id ,  @Valor

		END

		CLOSE c1
		deallocate c1